id: I801B9417
source: https://sakyaresearch.org
source_file: null
initial_creation_type: input
imported: '2022-06-18T20:15:54.179446'
last_modified: '2022-06-18T20:15:54.179459'
parser: null
source_metadata:
  title: Ratnagotravibhāga commentary (block print), colophon excerpt
  author: རོང་སྟོན་ཤེས་བྱ་ཀུན་རིག
  description: 'Digital version 1.0 {Tibetan}, diplomatic edition of witness A; master
    xml (completed: 2020-05-19); revision in process, thematic TEI markup'
  file_info:
  - 'Language: Tibetan'
  - 'Coverage: Excerpt/Colophon'
  - 'Accessible: publicly'
  responibilities:
  - Digital edition:ས་སྐྱ་ཞིབ་འཇུག་ཁང་། (src)
  - Text input:Mathias Fermer (mf)
  - Editorial process:-
  - TEI Encoding:ས་སྐྱ་ཞིབ་འཇུག་ཁང་།
  - TEI Markup:Mathias Fermer (mf)
  - Revisions/Corrections:Mathias Fermer (mf)
  text_witnesses: https://sakyaresearch.org/sources/1680
  bases:
    423f:
      title: Ratnagotravibhāga commentary (block print), colophon excerpt
      order: 1
      base_file: 423f.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
